[project]
name = "learn-ollama-code"
version = "0.1.0"
description = "Bash is all you need - A nano Claude Code–like agent for Ollama, built from 0 to 1"
readme = "README.md"
repository = "https://github.com/7shi/learn-ollama-code"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "ollama>=0.6.1",
    "gnureadline>=8.0.0; sys_platform == 'linux'",
    "colorama>=0.4.6",
]
